### PR TITLE
feat: Add the 2 new supported `v2/verify` payloads

### PR DESCRIPTION
**Pull request by viccuad**
## Description

Fix https://github.com/kubewarden/policy-sdk-rust/issues/40
Fix https://github.com/kubewarden/policy-sdk-rust/issues/41

## Test

Locally. See also on the automated build.

### CODE REVIEW

**Comment by viccuad** [comment]
Updated to match changes in https://github.com/kubewarden/policy-evaluator/pull/152.

**Comment by raulcabello** [comment]
@flavio which fields are missing? JSON objects looks good to me. I've used these objects like those for testing the verify-image-signatures policy

**Comment by viccuad** [comment]
this is ready for another review, with the latest changes in the callback payloads.

**Review by raulcabello — APPROVED** [review]

**Review by flavio — APPROVED** [review]
LGTM

**Pull request merged**
