### PR TITLE
feat: add a tiny stub page on JavaScript policies

### PR DESCRIPTION
**Pull request by agilgur5**
### Summary

Adds a tiny stub page on writing policies in JavaScript using [Javy](https://github.com/Shopify/javy)

### Details

- similar to the TypeScript stub page that just briefly mentions AssemblyScript
  - minus the example

- I found out about Javy recently, think it might deserve a mention
  - especially for potential eventual compatibility with [jsPolicy](https://github.com/loft-sh/jspolicy)
    policies, similar to how Kubewarden has some Rego/OPA/Gatekeeper compat
    

## Test

N/A

To test this pull request, you can run the following commands:

### Tradeoff

It's a stub, so not particularly useful and potentially even misleading, but it also shows potential users that there is opportunity for JS usage as well. Javy is also in beta, so could be abandoned, but it is also used by Shopify, so maybe not so likely. The stub is also transparent about the status, similar to the TypeScript stub.

### Potential improvement

Just informing the Kubewarden and broader WASM and Policy communities about Javy

### CODE REVIEW

**Comment by flavio** [comment]
@divya-mohan0209: something to be ported to docusaurus branch :sweat_smile:

**Comment by agilgur5** [comment]
Was curious to see if anyone else had made progress with JS and it looks like this page doesn't exist on the v1.10+ versions of the docs. Was that intentional?

**Comment by flavio** [comment]
We haven't working on adding JS as a supported language to write policies. We haven't received requests from the community, aside from this PR.

Would you mind opening a new issue on https://github.com/kubewarden/kubewarden-controller/ please?

**Comment by agilgur5** [comment]
I can, although the current ["Writing Policies" > "Other languages" page](https://docs.kubewarden.io/tutorials/writing-policies/other-languages) [says to](https://github.com/kubewarden/docs/blob/bb35cdd8ebc4f5088693ef62aada47d1800ba5b5/docs/tutorials/writing-policies/other-languages.md?plain=1#L19) open an issue or PR in _this_ repo.

And that makes more sense to me awareness-wise as people will read the docs. The Controller also isn't responsible for language support either, so an issue there would be confusing to me.

Since Javy and WASI have more stable adoption/usage these days, I was thinking of experimenting with both myself to support other languages (JS and Python as two very popular languages, with jsPolicy compat being nice to have too. I was looking at updating the Go WASI example too since the official compiler supports it better now too)

**Comment by flavio** [comment]
About where to open the issue, it's just that we use the controller repository as a central place to coordinate the work on bigger issue, like this one.

> Since Javy and WASI have more stable adoption/usage these days, I was thinking of experimenting with both myself to support other languages (JS and Python as two very popular languages, with jsPolicy compat being nice to have too (as per the original description).

Yes, they are definitely more mature solutions right now. The best way to implement support of these languages would be by adding a [waPC](https://github.com/wapc) guest driver for them.

A faster way (in terms of coding efforts) would be the writing of a [Kubewarden WASI](https://docs.kubewarden.io/tutorials/writing-policies/wasi/intro-wasi) policy, but this suffers some limitations (documented [here](https://docs.kubewarden.io/tutorials/writing-policies/wasi/intro-wasi#limitations)).

If you need some help feel free to join slack and ask. We'll be glad to help :)

> I was looking at updating the Go WASI example too since the official compiler supports it better now too)

What are you referring to?

**Comment by agilgur5** [comment]
> About where to open the issue, it's just that we use the controller repository as a central place to coordinate the work on bigger issue, like this one.

> A faster way (in terms of coding efforts) would be the writing of a [Kubewarden WASI](https://docs.kubewarden.io/tutorials/writing-policies/wasi/intro-wasi) policy, but this suffers some limitations (documented [here](https://docs.kubewarden.io/tutorials/writing-policies/wasi/intro-wasi#limitations)).

It looks like this effort has been moved to https://github.com/kubewarden/community/issues/37

> > I was looking at updating the Go WASI example too since the official compiler supports it better now too)
> 
> What are you referring to?

The current Go WASI template [uses TinyGo](https://github.com/kubewarden/go-policy-template/blob/8dd8ce5bee2267ce244fa48454cd1289b848f8b7/README.md#implementation-details), but Go has partial support for WASI preview 1 [since Go 1.21](https://go.dev/blog/wasi) / https://github.com/golang/go/issues/31105. The Kyverno policy also says its waPC support is blocked due to the lack of `go:wasmexport` directive / https://github.com/golang/go/issues/42372 -- it has been added in Go 1.24 per https://github.com/golang/go/issues/65199.
Supporting the official Go compiler could help adoption and reduce maintenance overhead, although I think there are still some desirable features from TinyGo (e.g. smaller binary size, better support for WASI preview 2)

**Pull request merged**
