### PR TITLE
Add call to action for policies to quickstart

### PR DESCRIPTION
**Pull request by viccuad**
I'm aware that we have other PRs refactoring quickstart, please feel free to close this PR and add this content on them.

### CODE REVIEW

**Review by jvanz — APPROVED** [review]

**Review by flavio — APPROVED** [review]
LGTM

@nunix: should we merge this PR or do you want to incorporate the change into your PR?

**Review by ereslibre — CHANGES_REQUESTED** [review]
LGTM, typo

**Review by flavio — APPROVED** [review]
thanks for the fix

**Comment by nunix** [comment]
Added the suggestion to #73

**Comment by flavio** [comment]
Thanks @nunix, we can then close this issue

**Pull request closed without merging**
