### PR TITLE
feat(docs): howto use policy groups.

### LINKED ISSUE #449: PolicyGroup: add howto page
Write a new page under the "Howtos" section that explains how to make use of the PolicyGroup feature.

We could copy examples from the examples made inside of the [RFC](https://github.com/kubewarden/rfc/blob/main/rfc/0021-policy-group.md)

### PR DESCRIPTION
**Pull request by jvanz**
## Description

Adds a new Howto page showing how to use the policy groups.

Fix #449

### CODE REVIEW

**Review by jhkrug — CHANGES_REQUESTED** [review]
Some suggestions for your consideration.

**Comment by flavio** [comment]
I would even close this PR. It's basically a shorted version of the explanation page provided by https://github.com/kubewarden/docs/pull/453

@jhkrug: what do you think, am I missing some nuance?

**Comment by jhkrug** [comment]
I thought they were quite similar, other than being in explanations and howtos. Maybe that's the distinction. Maybe another iteration of both, focusing on a better separation of the content into howto and explanation might be worth doing.

**Comment by jhkrug** [comment]
I think the whole first part could be replaced with:

Prior to working with Policy Groups, consult the [explanation](link) for them.

Then another look at what remains. The example is very similar to that in explanations. Say, something, like:

Using the example from [the explanation of Policy Groups](link to the example) use these commands to implement (or define) it.

Commands

Output.

That should do. The Context aware rules section is already covered in Context-Aware policies in the explanation (I think) so could be dispensed with.

What do you think?

**Comment by flavio** [comment]
@jhkrug I've made the changes you described

**Review by jhkrug — CHANGES_REQUESTED** [review]
Two little suggestions to consider, but otherwise lgtm.

**Comment by flavio** [comment]
@jhkrug thanks for the last review

**Pull request merged**
